// This file is auto-generated by tools/updateData/generateLocale.ts
import type { localeData } from "./index"
export default {
	LogicType: {
		Charge: "Laitteen nykyinen varaustaso",
		On: "Laitteen nykyinen status, 0 pois päältä, 1 päällä.",
		PowerRequired: "Ei muita luettavia laitteita verkostossa",
		RatioCarbonDioxide: "The ratio of Hiilidioksidi in device atmosphere",
		RatioCarbonDioxideInput: "The ratio of Hiilidioksidi in device's input network",
		RatioCarbonDioxideInput2: "The ratio of Hiilidioksidi in device's Input2 network",
		RatioCarbonDioxideOutput: "The ratio of Hiilidioksidi in device's Output network",
		RatioCarbonDioxideOutput2: "The ratio of Hiilidioksidi in device's Output2 network",
		RatioNitrousOxide: "The ratio of Typpimonoksidi in device atmosphere",
		RatioNitrousOxideInput: "The ratio of Typpimonoksidi in device's input network",
		RatioNitrousOxideInput2: "The ratio of Typpimonoksidi in device's Input2 network",
		RatioNitrousOxideOutput: "The ratio of Typpimonoksidi in device's Output network",
		RatioNitrousOxideOutput2: "The ratio of Typpimonoksidi in device's Output2 network",
	},
} satisfies localeData as localeData
