// This file is auto-generated by tools/updateData/generateLocale.ts
import type { localeData } from "./index"
export default {
	LogicType: {
		PowerRequired: "デバイスかネットワークに電力が必要",
		PrefabHash: "構造体のハッシュ",
		RatioCarbonDioxide: "The ratio of 二酸化炭素 in device atmosphere",
		RatioCarbonDioxideInput: "The ratio of 二酸化炭素 in device's input network",
		RatioCarbonDioxideInput2: "The ratio of 二酸化炭素 in device's Input2 network",
		RatioCarbonDioxideOutput: "The ratio of 二酸化炭素 in device's Output network",
		RatioCarbonDioxideOutput2: "The ratio of 二酸化炭素 in device's Output2 network",
		RatioNitrousOxide: "The ratio of 亜酸化窒素 in device atmosphere",
		RatioNitrousOxideInput: "The ratio of 亜酸化窒素 in device's input network",
		RatioNitrousOxideInput2: "The ratio of 亜酸化窒素 in device's Input2 network",
		RatioNitrousOxideOutput: "The ratio of 亜酸化窒素 in device's Output network",
		RatioNitrousOxideOutput2: "The ratio of 亜酸化窒素 in device's Output2 network",
	},
	label: "非推奨",
} satisfies localeData as localeData
