// This file is auto-generated by tools/updateData/generateLocale.ts
import type { localeData } from "./index"
export default {
	LogicType: {
		RatioCarbonDioxide: "The ratio of Koolstofdioxide in device atmosphere",
		RatioCarbonDioxideInput: "The ratio of Koolstofdioxide in device's input network",
		RatioCarbonDioxideInput2: "The ratio of Koolstofdioxide in device's Input2 network",
		RatioCarbonDioxideOutput: "The ratio of Koolstofdioxide in device's Output network",
		RatioCarbonDioxideOutput2: "The ratio of Koolstofdioxide in device's Output2 network",
		RatioNitrousOxide: "The ratio of Distikstofmonoxide in device atmosphere",
		RatioNitrousOxideInput: "The ratio of Distikstofmonoxide in device's input network",
		RatioNitrousOxideInput2: "The ratio of Distikstofmonoxide in device's Input2 network",
		RatioNitrousOxideOutput: "The ratio of Distikstofmonoxide in device's Output network",
		RatioNitrousOxideOutput2: "The ratio of Distikstofmonoxide in device's Output2 network",
	},
} satisfies localeData as localeData
