// This file is auto-generated by tools/updateData/generateLocale.ts
import type { localeData } from "./index"
export default {
	LogicType: {
		PowerRequired: "No other readable devices on network",
		RatioCarbonDioxide: "The ratio of Oxid Uhličitý in device atmosphere",
		RatioCarbonDioxideInput: "The ratio of Oxid Uhličitý in device's input network",
		RatioCarbonDioxideInput2: "The ratio of Oxid Uhličitý in device's Input2 network",
		RatioCarbonDioxideOutput: "The ratio of Oxid Uhličitý in device's Output network",
		RatioCarbonDioxideOutput2: "The ratio of Oxid Uhličitý in device's Output2 network",
	},
} satisfies localeData as localeData
