// This file is auto-generated by tools/updateData/generateLocale.ts
import type { localeData } from "./index"
export default {
	LogicType: {
		PowerRequired: "從設備和/或網路需求的電源",
		RatioCarbonDioxide: "The ratio of 二氧化碳 (Carbon Dioxide) in device atmosphere",
		RatioCarbonDioxideInput: "The ratio of 二氧化碳 (Carbon Dioxide) in device's input network",
		RatioCarbonDioxideInput2: "The ratio of 二氧化碳 (Carbon Dioxide) in device's Input2 network",
		RatioCarbonDioxideOutput: "The ratio of 二氧化碳 (Carbon Dioxide) in device's Output network",
		RatioCarbonDioxideOutput2: "The ratio of 二氧化碳 (Carbon Dioxide) in device's Output2 network",
		RatioNitrousOxide: "The ratio of 氧化亞氮 (Nitrous Oxide) in device atmosphere",
		RatioNitrousOxideInput: "The ratio of 氧化亞氮 (Nitrous Oxide) in device's input network",
		RatioNitrousOxideInput2: "The ratio of 氧化亞氮 (Nitrous Oxide) in device's Input2 network",
		RatioNitrousOxideOutput: "The ratio of 氧化亞氮 (Nitrous Oxide) in device's Output network",
		RatioNitrousOxideOutput2: "The ratio of 氧化亞氮 (Nitrous Oxide) in device's Output2 network",
	},
	label: "已棄用",
} satisfies localeData as localeData
