import { writeFile } from "node:fs/promises"
import z from "zod"
import { kindEnum } from "../../src/enums"
import { row, stringifyHtml } from "."

export default async function updateLogicAndConstants() {
	const constants = await fetch("https://assets.ic10.dev/languages/EN/constants.json").then((res) => res.json())

	const descriptions: Map<string, string> = await fetch("https://assets.ic10.dev/languages/EN/logics.json")
		.then((res) => res.json())
		.then((data) => {
			const map: Map<string, string> = new Map()
			for (const entry of data.data) {
				if (!entry.name || entry.name.length === 0) continue
				if (!entry.description || entry.description.length === 0) continue
				map.set(entry.name, entry.description)
			}
			return map
		})
	const constant = z.object({
		literal: z.string().min(1),
		description: z.string().optional(),
		value: z.number().or(z.nan()).or(z.literal(Infinity)).or(z.literal(-Infinity)),
		deprecated: z.boolean().optional(),
		kind: z.union(Object.values(kindEnum).map((v) => z.literal(v))),
	})

	type constant = z.infer<typeof constant>
	const constantList: Map<string, constant> = new Map()
	const logicList: Map<string, constant> = new Map()

	// parce constants if entry starts with Logic add it to logic else to consts
	// skip if canUseAsConst is false

	function getEntryLiteral(entry: any): constant | null {
		if (entry.canUseAsConst === false) return null

		// console.log(entry.name, descriptions.get(entry.name));
		const description = stringifyHtml(descriptions.get(entry.literal) || entry.description || "") || undefined
		// console.log(description);
		const result = {
			literal: entry.literal,
			description,
			value: Number(entry.value),
			deprecated: entry.deprecated || undefined,
			kind:
				entry.referenceType in kindEnum
					? kindEnum[entry.referenceType as keyof typeof kindEnum]
					: entry.referenceType,
		}
		if (Number.isNaN(result.value) && entry.value !== "NaN") {
			console.warn(`Invalid constant value: ${entry.literal} got ${entry.value}`)
			return null
		}
		const parseResult = constant.safeParse(result)
		if (!parseResult.success) {
			console.warn(`Failed to parse constant: ${entry.literal}`, parseResult.error.message)
			return null
		}
		return parseResult.data
	}

	for (const raw of Object.entries(constants)) {
		const entry = raw[1]
		const parsed = getEntryLiteral(entry)
		if (!parsed) continue
		if (parsed.literal !== raw[0]) {
			console.log(parsed.literal, raw[0])
			continue
		}
		if (parsed.literal.startsWith("Logic")) logicList.set(parsed.literal, parsed)
		else constantList.set(parsed.literal, parsed)
	}
	// got x logicList and constantList
	console.log(`Fetched ${constantList.size} constant entries`)
	console.log(`Fetched ${logicList.size} logic entries`)

	// write to src/data/constants.ts and src/data/logic.ts
	// export const constants: {
	// 	name: string
	// 	description: string
	// }[] = [
	// 	{ name: "nan", description: "nan = NaN" },
	// 	{ name: "pinf", description: "pinf = Infinity" },
	// ]

	function generateDataFile(constants: Map<string, constant>): string {
		const type =
			`{\n` +
			row(`literal: string`, 1) +
			row(`description?: string`, 1) +
			row(`value: number`, 1) +
			row(`deprecated?: boolean`, 1) +
			row(`kind: 0 | 1`, 1) +
			`}[]`
		let fileContent = `// This file is auto-generated by tools/updateData/index.ts\n`
		fileContent += `export default [\n`
		for (const constant of constants.values()) {
			fileContent += row(`{`, 1)
			fileContent += row(`literal: ${JSON.stringify(constant.literal)},`, 2)
			if (constant.description) fileContent += row(`description: ${JSON.stringify(constant.description)},`, 2)
			fileContent += row(`value: ${constant.value},`, 2)
			if (constant.deprecated) fileContent += row(`deprecated: ${constant.deprecated},`, 2)
			fileContent += row(`kind: ${constant.kind},`, 2)
			fileContent += row(`},`, 1)
		}
		fileContent += `] satisfies `
		fileContent += type
		fileContent += ` as `
		fileContent += type
		fileContent += `\n`

		return fileContent
	}

	const constantsFileContent = generateDataFile(constantList)
	const logicFileContent = generateDataFile(logicList)

	await writeFile("src/data/constants.ts", constantsFileContent, "utf-8")
	await writeFile("src/data/logic.ts", logicFileContent, "utf-8")
}
