// This file is auto-generated by tools/updateData/index.ts
import type { nestedData } from "."
export default {
	AirCon: {
		Cold: {
			literal: "AirCon.Cold",
			value: 0,
			kind: 1,
		},
		Hot: {
			literal: "AirCon.Hot",
			value: 1,
			kind: 1,
		},
	},
	AirControl: {
		Draught: {
			literal: "AirControl.Draught",
			value: 4,
			kind: 1,
		},
		None: {
			literal: "AirControl.None",
			value: 0,
			kind: 1,
		},
		Offline: {
			literal: "AirControl.Offline",
			value: 1,
			kind: 1,
		},
		Pressure: {
			literal: "AirControl.Pressure",
			value: 2,
			kind: 1,
		},
	},
	Color: {
		Black: {
			literal: "Color.Black",
			value: 7,
			kind: 1,
		},
		Blue: {
			literal: "Color.Blue",
			value: 0,
			kind: 1,
		},
		Brown: {
			literal: "Color.Brown",
			value: 8,
			kind: 1,
		},
		Gray: {
			literal: "Color.Gray",
			value: 1,
			kind: 1,
		},
		Green: {
			literal: "Color.Green",
			value: 2,
			kind: 1,
		},
		Khaki: {
			literal: "Color.Khaki",
			value: 9,
			kind: 1,
		},
		Orange: {
			literal: "Color.Orange",
			value: 3,
			kind: 1,
		},
		Pink: {
			literal: "Color.Pink",
			value: 10,
			kind: 1,
		},
		Purple: {
			literal: "Color.Purple",
			value: 11,
			kind: 1,
		},
		Red: {
			literal: "Color.Red",
			value: 4,
			kind: 1,
		},
		White: {
			literal: "Color.White",
			value: 6,
			kind: 1,
		},
		Yellow: {
			literal: "Color.Yellow",
			value: 5,
			kind: 1,
		},
	},
	ConditionOperation: {
		Equals: {
			literal: "ConditionOperation.Equals",
			value: 0,
			kind: 1,
		},
		Greater: {
			literal: "ConditionOperation.Greater",
			value: 1,
			kind: 1,
		},
		Less: {
			literal: "ConditionOperation.Less",
			value: 2,
			kind: 1,
		},
		NotEquals: {
			literal: "ConditionOperation.NotEquals",
			value: 3,
			kind: 1,
		},
	},
	ContactTier: {
		Close: {
			literal: "ContactTier.Close",
			value: 0,
			kind: 1,
		},
		Far: {
			literal: "ContactTier.Far",
			value: 2,
			kind: 1,
		},
		Medium: {
			literal: "ContactTier.Medium",
			value: 1,
			kind: 1,
		},
	},
	DaylightSensorMode: {
		Default: {
			literal: "DaylightSensorMode.Default",
			value: 0,
			kind: 1,
		},
		Horizontal: {
			literal: "DaylightSensorMode.Horizontal",
			value: 1,
			kind: 1,
		},
		Vertical: {
			literal: "DaylightSensorMode.Vertical",
			value: 2,
			kind: 1,
		},
	},
	DisplayMode: {
		Celsius: {
			literal: "DisplayMode.Celsius",
			value: 4,
			kind: 1,
		},
		Credits: {
			literal: "DisplayMode.Credits",
			value: 6,
			kind: 1,
		},
		Days: {
			literal: "DisplayMode.Days",
			value: 9,
			kind: 1,
		},
		Default: {
			literal: "DisplayMode.Default",
			value: 0,
			kind: 1,
		},
		Fahrenheit: {
			literal: "DisplayMode.Fahrenheit",
			value: 11,
			kind: 1,
		},
		Kelvin: {
			literal: "DisplayMode.Kelvin",
			value: 3,
			kind: 1,
		},
		Litres: {
			literal: "DisplayMode.Litres",
			value: 12,
			kind: 1,
		},
		Meters: {
			literal: "DisplayMode.Meters",
			value: 5,
			kind: 1,
		},
		Minutes: {
			literal: "DisplayMode.Minutes",
			value: 8,
			kind: 1,
		},
		Mol: {
			literal: "DisplayMode.Mol",
			value: 13,
			kind: 1,
		},
		Pa: {
			literal: "DisplayMode.Pa",
			value: 14,
			kind: 1,
		},
		Percent: {
			literal: "DisplayMode.Percent",
			value: 1,
			kind: 1,
		},
		Power: {
			literal: "DisplayMode.Power",
			value: 2,
			kind: 1,
		},
		Seconds: {
			literal: "DisplayMode.Seconds",
			value: 7,
			kind: 1,
		},
		String: {
			literal: "DisplayMode.String",
			value: 10,
			kind: 1,
		},
	},
	ElevatorMode: {
		Downward: {
			literal: "ElevatorMode.Downward",
			value: 2,
			kind: 1,
		},
		Stationary: {
			literal: "ElevatorMode.Stationary",
			value: 0,
			kind: 1,
		},
		Upward: {
			literal: "ElevatorMode.Upward",
			value: 1,
			kind: 1,
		},
	},
	EntityState: {
		Alive: {
			literal: "EntityState.Alive",
			value: 0,
			kind: 1,
		},
		Dead: {
			literal: "EntityState.Dead",
			value: 1,
			kind: 1,
		},
		Decay: {
			literal: "EntityState.Decay",
			value: 3,
			kind: 1,
		},
		Unconscious: {
			literal: "EntityState.Unconscious",
			value: 2,
			kind: 1,
		},
	},
	GasType: {
		Air: {
			literal: "GasType.Air",
			value: 3,
			kind: 1,
		},
		CarbonDioxide: {
			literal: "GasType.CarbonDioxide",
			value: 4,
			kind: 1,
		},
		Fuel: {
			literal: "GasType.Fuel",
			value: 9,
			kind: 1,
		},
		Hydrogen: {
			literal: "GasType.Hydrogen",
			value: 16384,
			kind: 1,
		},
		LiquidCarbonDioxide: {
			literal: "GasType.LiquidCarbonDioxide",
			value: 2048,
			kind: 1,
		},
		LiquidHydrogen: {
			literal: "GasType.LiquidHydrogen",
			value: 32768,
			kind: 1,
		},
		LiquidNitrogen: {
			literal: "GasType.LiquidNitrogen",
			value: 128,
			kind: 1,
		},
		LiquidNitrousOxide: {
			literal: "GasType.LiquidNitrousOxide",
			value: 8192,
			kind: 1,
		},
		LiquidOxygen: {
			literal: "GasType.LiquidOxygen",
			value: 256,
			kind: 1,
		},
		LiquidPollutant: {
			literal: "GasType.LiquidPollutant",
			value: 4096,
			kind: 1,
		},
		LiquidVolatiles: {
			literal: "GasType.LiquidVolatiles",
			value: 512,
			kind: 1,
		},
		Nitrogen: {
			literal: "GasType.Nitrogen",
			value: 2,
			kind: 1,
		},
		NitrousOxide: {
			literal: "GasType.NitrousOxide",
			value: 64,
			kind: 1,
		},
		Oxygen: {
			literal: "GasType.Oxygen",
			value: 1,
			kind: 1,
		},
		Pollutant: {
			literal: "GasType.Pollutant",
			value: 16,
			kind: 1,
		},
		PollutedWater: {
			literal: "GasType.PollutedWater",
			value: 65536,
			kind: 1,
		},
		Steam: {
			literal: "GasType.Steam",
			value: 1024,
			kind: 1,
		},
		Undefined: {
			literal: "GasType.Undefined",
			value: 0,
			kind: 1,
		},
		Volatiles: {
			literal: "GasType.Volatiles",
			value: 8,
			kind: 1,
		},
		Water: {
			literal: "GasType.Water",
			value: 32,
			kind: 1,
		},
	},
	HashType: {
		GasLiquid: {
			literal: "HashType.GasLiquid",
			value: 1,
			kind: 1,
		},
		Prefab: {
			literal: "HashType.Prefab",
			value: 0,
			kind: 1,
		},
	},
	PowerMode: {
		Charged: {
			literal: "PowerMode.Charged",
			value: 4,
			kind: 1,
		},
		Charging: {
			literal: "PowerMode.Charging",
			value: 3,
			kind: 1,
		},
		Discharged: {
			literal: "PowerMode.Discharged",
			value: 1,
			kind: 1,
		},
		Discharging: {
			literal: "PowerMode.Discharging",
			value: 2,
			kind: 1,
		},
		Idle: {
			literal: "PowerMode.Idle",
			value: 0,
			kind: 1,
		},
	},
	PrinterInstruction: {
		DeviceSetLock: {
			literal: "PrinterInstruction.DeviceSetLock",
			value: 6,
			kind: 1,
		},
		EjectAllReagents: {
			literal: "PrinterInstruction.EjectAllReagents",
			value: 8,
			kind: 1,
		},
		EjectReagent: {
			literal: "PrinterInstruction.EjectReagent",
			value: 7,
			kind: 1,
		},
		ExecuteRecipe: {
			literal: "PrinterInstruction.ExecuteRecipe",
			value: 2,
			kind: 1,
		},
		JumpIfNextInvalid: {
			literal: "PrinterInstruction.JumpIfNextInvalid",
			value: 4,
			kind: 1,
		},
		JumpToAddress: {
			literal: "PrinterInstruction.JumpToAddress",
			value: 5,
			kind: 1,
		},
		MissingRecipeReagent: {
			literal: "PrinterInstruction.MissingRecipeReagent",
			value: 9,
			kind: 1,
		},
		None: {
			literal: "PrinterInstruction.None",
			value: 0,
			kind: 1,
		},
		StackPointer: {
			literal: "PrinterInstruction.StackPointer",
			value: 1,
			kind: 1,
		},
		WaitUntilNextValid: {
			literal: "PrinterInstruction.WaitUntilNextValid",
			value: 3,
			kind: 1,
		},
	},
	ReEntryProfile: {
		High: {
			literal: "ReEntryProfile.High",
			value: 3,
			kind: 1,
		},
		Low: {
			literal: "ReEntryProfile.Low",
			value: 1,
			kind: 1,
		},
		Max: {
			literal: "ReEntryProfile.Max",
			value: 4,
			kind: 1,
		},
		Medium: {
			literal: "ReEntryProfile.Medium",
			value: 2,
			kind: 1,
		},
		None: {
			literal: "ReEntryProfile.None",
			value: 0,
			kind: 1,
		},
	},
	RobotMode: {
		Follow: {
			literal: "RobotMode.Follow",
			value: 1,
			kind: 1,
		},
		MoveToTarget: {
			literal: "RobotMode.MoveToTarget",
			value: 2,
			kind: 1,
		},
		None: {
			literal: "RobotMode.None",
			value: 0,
			kind: 1,
		},
		PathToTarget: {
			literal: "RobotMode.PathToTarget",
			value: 5,
			kind: 1,
		},
		Roam: {
			literal: "RobotMode.Roam",
			value: 3,
			kind: 1,
		},
		StorageFull: {
			literal: "RobotMode.StorageFull",
			value: 6,
			kind: 1,
		},
		Unload: {
			literal: "RobotMode.Unload",
			value: 4,
			kind: 1,
		},
	},
	RocketMode: {
		Chart: {
			literal: "RocketMode.Chart",
			value: 5,
			kind: 1,
		},
		Deploy: {
			literal: "RocketMode.Deploy",
			value: 6,
			kind: 1,
		},
		Discover: {
			literal: "RocketMode.Discover",
			value: 4,
			kind: 1,
		},
		Invalid: {
			literal: "RocketMode.Invalid",
			value: 0,
			kind: 1,
		},
		Mine: {
			literal: "RocketMode.Mine",
			value: 2,
			kind: 1,
		},
		None: {
			literal: "RocketMode.None",
			value: 1,
			kind: 1,
		},
		Survey: {
			literal: "RocketMode.Survey",
			value: 3,
			kind: 1,
		},
	},
	SettingDisplayMode: {
		Number: {
			literal: "SettingDisplayMode.Number",
			value: 0,
			kind: 1,
		},
		String: {
			literal: "SettingDisplayMode.String",
			value: 1,
			kind: 1,
		},
	},
	ShuttleType: {
		Large: {
			literal: "ShuttleType.Large",
			value: 5,
			kind: 1,
		},
		LargeGas: {
			literal: "ShuttleType.LargeGas",
			value: 6,
			kind: 1,
		},
		LargePlane: {
			literal: "ShuttleType.LargePlane",
			value: 8,
			kind: 1,
		},
		Medium: {
			literal: "ShuttleType.Medium",
			value: 3,
			kind: 1,
		},
		MediumGas: {
			literal: "ShuttleType.MediumGas",
			value: 4,
			kind: 1,
		},
		MediumPlane: {
			literal: "ShuttleType.MediumPlane",
			value: 7,
			kind: 1,
		},
		None: {
			literal: "ShuttleType.None",
			value: 0,
			kind: 1,
		},
		Small: {
			literal: "ShuttleType.Small",
			value: 1,
			kind: 1,
		},
		SmallGas: {
			literal: "ShuttleType.SmallGas",
			value: 2,
			kind: 1,
		},
	},
	SlotClass: {
		AccessCard: {
			literal: "SlotClass.AccessCard",
			value: 22,
			kind: 1,
		},
		Appliance: {
			literal: "SlotClass.Appliance",
			value: 18,
			kind: 1,
		},
		Back: {
			literal: "SlotClass.Back",
			value: 3,
			kind: 1,
		},
		Battery: {
			literal: "SlotClass.Battery",
			value: 14,
			kind: 1,
		},
		Belt: {
			literal: "SlotClass.Belt",
			value: 16,
			kind: 1,
		},
		Blocked: {
			literal: "SlotClass.Blocked",
			value: 38,
			kind: 1,
		},
		Bottle: {
			literal: "SlotClass.Bottle",
			value: 25,
			kind: 1,
		},
		Cartridge: {
			literal: "SlotClass.Cartridge",
			value: 21,
			kind: 1,
		},
		Circuit: {
			literal: "SlotClass.Circuit",
			value: 24,
			kind: 1,
		},
		Circuitboard: {
			literal: "SlotClass.Circuitboard",
			value: 7,
			kind: 1,
		},
		Crate: {
			literal: "SlotClass.Crate",
			value: 40,
			kind: 1,
		},
		CreditCard: {
			literal: "SlotClass.CreditCard",
			value: 28,
			kind: 1,
		},
		DataDisk: {
			literal: "SlotClass.DataDisk",
			value: 8,
			kind: 1,
		},
		DirtCanister: {
			literal: "SlotClass.DirtCanister",
			value: 29,
			kind: 1,
		},
		DrillHead: {
			literal: "SlotClass.DrillHead",
			value: 35,
			kind: 1,
		},
		Egg: {
			literal: "SlotClass.Egg",
			value: 15,
			kind: 1,
		},
		Entity: {
			literal: "SlotClass.Entity",
			value: 13,
			kind: 1,
		},
		Flare: {
			literal: "SlotClass.Flare",
			value: 37,
			kind: 1,
		},
		GasCanister: {
			literal: "SlotClass.GasCanister",
			value: 5,
			kind: 1,
		},
		GasFilter: {
			literal: "SlotClass.GasFilter",
			value: 4,
			kind: 1,
		},
		Glasses: {
			literal: "SlotClass.Glasses",
			value: 27,
			kind: 1,
		},
		Helmet: {
			literal: "SlotClass.Helmet",
			value: 1,
			kind: 1,
		},
		Ingot: {
			literal: "SlotClass.Ingot",
			value: 19,
			kind: 1,
		},
		LiquidBottle: {
			literal: "SlotClass.LiquidBottle",
			value: 32,
			kind: 1,
		},
		LiquidCanister: {
			literal: "SlotClass.LiquidCanister",
			value: 31,
			kind: 1,
		},
		Magazine: {
			literal: "SlotClass.Magazine",
			value: 23,
			kind: 1,
		},
		Motherboard: {
			literal: "SlotClass.Motherboard",
			value: 6,
			kind: 1,
		},
		None: {
			literal: "SlotClass.None",
			value: 0,
			kind: 1,
		},
		Ore: {
			literal: "SlotClass.Ore",
			value: 10,
			kind: 1,
		},
		Organ: {
			literal: "SlotClass.Organ",
			value: 9,
			kind: 1,
		},
		Plant: {
			literal: "SlotClass.Plant",
			value: 11,
			kind: 1,
		},
		Portables: {
			literal: "SlotClass.Portables",
			value: 41,
			kind: 1,
		},
		ProgrammableChip: {
			literal: "SlotClass.ProgrammableChip",
			value: 26,
			kind: 1,
		},
		RocketPayload: {
			literal: "SlotClass.RocketPayload",
			value: 42,
			kind: 1,
		},
		ScanningHead: {
			literal: "SlotClass.ScanningHead",
			value: 36,
			kind: 1,
		},
		SensorProcessingUnit: {
			literal: "SlotClass.SensorProcessingUnit",
			value: 30,
			kind: 1,
		},
		SoundCartridge: {
			literal: "SlotClass.SoundCartridge",
			value: 34,
			kind: 1,
		},
		Suit: {
			literal: "SlotClass.Suit",
			value: 2,
			kind: 1,
		},
		SuitMod: {
			literal: "SlotClass.SuitMod",
			value: 39,
			kind: 1,
		},
		Tool: {
			literal: "SlotClass.Tool",
			value: 17,
			kind: 1,
		},
		Torpedo: {
			literal: "SlotClass.Torpedo",
			value: 20,
			kind: 1,
		},
		Uniform: {
			literal: "SlotClass.Uniform",
			value: 12,
			kind: 1,
		},
		Wreckage: {
			literal: "SlotClass.Wreckage",
			value: 33,
			kind: 1,
		},
	},
	SorterInstruction: {
		FilterPrefabHashEquals: {
			literal: "SorterInstruction.FilterPrefabHashEquals",
			value: 1,
			kind: 1,
		},
		FilterPrefabHashNotEquals: {
			literal: "SorterInstruction.FilterPrefabHashNotEquals",
			value: 2,
			kind: 1,
		},
		FilterQuantityCompare: {
			literal: "SorterInstruction.FilterQuantityCompare",
			value: 5,
			kind: 1,
		},
		FilterSlotTypeCompare: {
			literal: "SorterInstruction.FilterSlotTypeCompare",
			value: 4,
			kind: 1,
		},
		FilterSortingClassCompare: {
			literal: "SorterInstruction.FilterSortingClassCompare",
			value: 3,
			kind: 1,
		},
		LimitNextExecutionByCount: {
			literal: "SorterInstruction.LimitNextExecutionByCount",
			value: 6,
			kind: 1,
		},
		None: {
			literal: "SorterInstruction.None",
			value: 0,
			kind: 1,
		},
	},
	SortingClass: {
		Appliances: {
			literal: "SortingClass.Appliances",
			value: 6,
			kind: 1,
		},
		Atmospherics: {
			literal: "SortingClass.Atmospherics",
			value: 7,
			kind: 1,
		},
		Clothing: {
			literal: "SortingClass.Clothing",
			value: 5,
			kind: 1,
		},
		Default: {
			literal: "SortingClass.Default",
			value: 0,
			kind: 1,
		},
		Food: {
			literal: "SortingClass.Food",
			value: 4,
			kind: 1,
		},
		Ices: {
			literal: "SortingClass.Ices",
			value: 10,
			kind: 1,
		},
		Kits: {
			literal: "SortingClass.Kits",
			value: 1,
			kind: 1,
		},
		Ores: {
			literal: "SortingClass.Ores",
			value: 9,
			kind: 1,
		},
		Resources: {
			literal: "SortingClass.Resources",
			value: 3,
			kind: 1,
		},
		Storage: {
			literal: "SortingClass.Storage",
			value: 8,
			kind: 1,
		},
		Tools: {
			literal: "SortingClass.Tools",
			value: 2,
			kind: 1,
		},
	},
	Sound: {
		AirlockCycling: {
			literal: "Sound.AirlockCycling",
			value: 22,
			kind: 1,
		},
		Alarm1: {
			literal: "Sound.Alarm1",
			value: 45,
			kind: 1,
		},
		Alarm10: {
			literal: "Sound.Alarm10",
			value: 12,
			kind: 1,
		},
		Alarm11: {
			literal: "Sound.Alarm11",
			value: 13,
			kind: 1,
		},
		Alarm12: {
			literal: "Sound.Alarm12",
			value: 14,
			kind: 1,
		},
		Alarm2: {
			literal: "Sound.Alarm2",
			value: 1,
			kind: 1,
		},
		Alarm3: {
			literal: "Sound.Alarm3",
			value: 2,
			kind: 1,
		},
		Alarm4: {
			literal: "Sound.Alarm4",
			value: 3,
			kind: 1,
		},
		Alarm5: {
			literal: "Sound.Alarm5",
			value: 4,
			kind: 1,
		},
		Alarm6: {
			literal: "Sound.Alarm6",
			value: 5,
			kind: 1,
		},
		Alarm7: {
			literal: "Sound.Alarm7",
			value: 6,
			kind: 1,
		},
		Alarm8: {
			literal: "Sound.Alarm8",
			value: 10,
			kind: 1,
		},
		Alarm9: {
			literal: "Sound.Alarm9",
			value: 11,
			kind: 1,
		},
		Alert: {
			literal: "Sound.Alert",
			value: 17,
			kind: 1,
		},
		Danger: {
			literal: "Sound.Danger",
			value: 15,
			kind: 1,
		},
		Depressurising: {
			literal: "Sound.Depressurising",
			value: 20,
			kind: 1,
		},
		FireFireFire: {
			literal: "Sound.FireFireFire",
			value: 28,
			kind: 1,
		},
		Five: {
			literal: "Sound.Five",
			value: 33,
			kind: 1,
		},
		Floor: {
			literal: "Sound.Floor",
			value: 34,
			kind: 1,
		},
		Four: {
			literal: "Sound.Four",
			value: 32,
			kind: 1,
		},
		HaltWhoGoesThere: {
			literal: "Sound.HaltWhoGoesThere",
			value: 27,
			kind: 1,
		},
		HighCarbonDioxide: {
			literal: "Sound.HighCarbonDioxide",
			value: 44,
			kind: 1,
		},
		IntruderAlert: {
			literal: "Sound.IntruderAlert",
			value: 19,
			kind: 1,
		},
		LiftOff: {
			literal: "Sound.LiftOff",
			value: 36,
			kind: 1,
		},
		MalfunctionDetected: {
			literal: "Sound.MalfunctionDetected",
			value: 26,
			kind: 1,
		},
		Music1: {
			literal: "Sound.Music1",
			value: 7,
			kind: 1,
		},
		Music2: {
			literal: "Sound.Music2",
			value: 8,
			kind: 1,
		},
		Music3: {
			literal: "Sound.Music3",
			value: 9,
			kind: 1,
		},
		None: {
			literal: "Sound.None",
			value: 0,
			kind: 1,
		},
		One: {
			literal: "Sound.One",
			value: 29,
			kind: 1,
		},
		PollutantsDetected: {
			literal: "Sound.PollutantsDetected",
			value: 43,
			kind: 1,
		},
		PowerLow: {
			literal: "Sound.PowerLow",
			value: 23,
			kind: 1,
		},
		PressureHigh: {
			literal: "Sound.PressureHigh",
			value: 39,
			kind: 1,
		},
		PressureLow: {
			literal: "Sound.PressureLow",
			value: 40,
			kind: 1,
		},
		Pressurising: {
			literal: "Sound.Pressurising",
			value: 21,
			kind: 1,
		},
		RocketLaunching: {
			literal: "Sound.RocketLaunching",
			value: 35,
			kind: 1,
		},
		StormIncoming: {
			literal: "Sound.StormIncoming",
			value: 18,
			kind: 1,
		},
		SystemFailure: {
			literal: "Sound.SystemFailure",
			value: 24,
			kind: 1,
		},
		TemperatureHigh: {
			literal: "Sound.TemperatureHigh",
			value: 41,
			kind: 1,
		},
		TemperatureLow: {
			literal: "Sound.TemperatureLow",
			value: 42,
			kind: 1,
		},
		Three: {
			literal: "Sound.Three",
			value: 31,
			kind: 1,
		},
		TraderIncoming: {
			literal: "Sound.TraderIncoming",
			value: 37,
			kind: 1,
		},
		TraderLanded: {
			literal: "Sound.TraderLanded",
			value: 38,
			kind: 1,
		},
		Two: {
			literal: "Sound.Two",
			value: 30,
			kind: 1,
		},
		Warning: {
			literal: "Sound.Warning",
			value: 16,
			kind: 1,
		},
		Welcome: {
			literal: "Sound.Welcome",
			value: 25,
			kind: 1,
		},
	},
	TraderInstruction: {
		FilterGasContains: {
			literal: "TraderInstruction.FilterGasContains",
			value: 17,
			kind: 1,
		},
		FilterGasNotContains: {
			literal: "TraderInstruction.FilterGasNotContains",
			value: 18,
			kind: 1,
		},
		FilterPrefabHashEquals: {
			literal: "TraderInstruction.FilterPrefabHashEquals",
			value: 13,
			kind: 1,
		},
		FilterPrefabHashNotEquals: {
			literal: "TraderInstruction.FilterPrefabHashNotEquals",
			value: 14,
			kind: 1,
		},
		FilterQuantityCompare: {
			literal: "TraderInstruction.FilterQuantityCompare",
			value: 16,
			kind: 1,
		},
		FilterSortingClassCompare: {
			literal: "TraderInstruction.FilterSortingClassCompare",
			value: 15,
			kind: 1,
		},
		None: {
			literal: "TraderInstruction.None",
			value: 0,
			kind: 1,
		},
		StrongestContactIdHash: {
			literal: "TraderInstruction.StrongestContactIdHash",
			value: 2,
			kind: 1,
		},
		StrongestContactMetaData: {
			literal: "TraderInstruction.StrongestContactMetaData",
			value: 3,
			kind: 1,
		},
		StrongestContactSignalData: {
			literal: "TraderInstruction.StrongestContactSignalData",
			value: 4,
			kind: 1,
		},
		TraderBuyGasData: {
			literal: "TraderInstruction.TraderBuyGasData",
			value: 9,
			kind: 1,
		},
		TraderBuyThingChildData: {
			literal: "TraderInstruction.TraderBuyThingChildData",
			value: 8,
			kind: 1,
		},
		TraderBuyThingData: {
			literal: "TraderInstruction.TraderBuyThingData",
			value: 7,
			kind: 1,
		},
		TraderSellGasData: {
			literal: "TraderInstruction.TraderSellGasData",
			value: 11,
			kind: 1,
		},
		TraderSellThingChildData: {
			literal: "TraderInstruction.TraderSellThingChildData",
			value: 12,
			kind: 1,
		},
		TraderSellThingData: {
			literal: "TraderInstruction.TraderSellThingData",
			value: 10,
			kind: 1,
		},
		WriteTraderBuyData: {
			literal: "TraderInstruction.WriteTraderBuyData",
			value: 5,
			kind: 1,
		},
		WriteTraderData: {
			literal: "TraderInstruction.WriteTraderData",
			value: 1,
			kind: 1,
		},
		WriteTraderSellData: {
			literal: "TraderInstruction.WriteTraderSellData",
			value: 6,
			kind: 1,
		},
	},
	TransmitterMode: {
		Active: {
			literal: "TransmitterMode.Active",
			value: 1,
			kind: 1,
		},
		Passive: {
			literal: "TransmitterMode.Passive",
			value: 0,
			kind: 1,
		},
	},
	Vent: {
		Inward: {
			literal: "Vent.Inward",
			value: 1,
			kind: 1,
		},
		Outward: {
			literal: "Vent.Outward",
			value: 0,
			kind: 1,
		},
	},
	deg2rad: {
		literal: "deg2rad",
		value: 0.01745329238474369,
		kind: 0,
	},
	epsilon: {
		literal: "epsilon",
		value: 5e-324,
		kind: 0,
	},
	nan: {
		literal: "nan",
		value: NaN,
		kind: 0,
	},
	ninf: {
		literal: "ninf",
		value: -Infinity,
		kind: 0,
	},
	pi: {
		literal: "pi",
		value: 3.141592653589793,
		kind: 0,
	},
	pinf: {
		literal: "pinf",
		value: Infinity,
		kind: 0,
	},
	rad2deg: {
		literal: "rad2deg",
		value: 57.295780181884766,
		kind: 0,
	},
	rgas: {
		literal: "rgas",
		value: 8.31446261815324,
		kind: 0,
	},
	tau: {
		literal: "tau",
		value: 6.283185307179586,
		kind: 0,
	},
} satisfies nestedData as nestedData
