// This file is auto-generated by tools/updateData/index.ts
export default [
	{
		name: "abs",
		snippet: "${1:r0} $0",
		preview: "abs r? a(r?|num)",
	},
	{
		name: "acos",
		snippet: "${1:r0} $0",
		preview: "acos r? a(r?|num)",
	},
	{
		name: "add",
		snippet: "${1:r0} $2 $0",
		preview: "add r? a(r?|num) b(r?|num)",
	},
	{
		name: "alias",
		snippet: "$1 ${0:r0}",
		preview: "alias str r?|d?",
	},
	{
		name: "and",
		snippet: "${1:r0} $2 $0",
		preview: "and r? a(r?|num) b(r?|num)",
	},
	{
		name: "asin",
		snippet: "${1:r0} $0",
		preview: "asin r? a(r?|num)",
	},
	{
		name: "atan",
		snippet: "${1:r0} $0",
		preview: "atan r? a(r?|num)",
	},
	{
		name: "atan2",
		snippet: "${1:r0} $2 $0",
		preview: "atan2 r? a(r?|num) b(r?|num)",
	},
	{
		name: "bap",
		snippet: "$1 $2 $3 $0",
		preview: "bap a(r?|num) b(r?|num) c(r?|num) d(r?|num)",
	},
	{
		name: "bapal",
		snippet: "$1 $2 $3 $0",
		preview: "bapal a(r?|num) b(r?|num) c(r?|num) d(r?|num)",
	},
	{
		name: "bapz",
		snippet: "$1 $2 $0",
		preview: "bapz a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bapzal",
		snippet: "$1 $2 $0",
		preview: "bapzal a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bdns",
		snippet: "${1:d0} $0",
		preview: "bdns device(d?|r?|id) a(r?|num)",
	},
	{
		name: "bdnsal",
		snippet: "${1:d0} $0",
		preview: "bdnsal device(d?|r?|id) a(r?|num)",
	},
	{
		name: "bdnvl",
		snippet: "${1:d0} $2 $0}",
		preview: "bdnvl device(d?|r?|id) logicType a(r?|num)",
	},
	{
		name: "bdnvs",
		snippet: "${1:d0} $2 $0}",
		preview: "bdnvs device(d?|r?|id) logicType a(r?|num)",
	},
	{
		name: "bdse",
		snippet: "${1:d0} $0",
		preview: "bdse device(d?|r?|id) a(r?|num)",
	},
	{
		name: "bdseal",
		snippet: "${1:d0} $0",
		preview: "bdseal device(d?|r?|id) a(r?|num)",
	},
	{
		name: "beq",
		snippet: "$1 $2 $0",
		preview: "beq a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "beqal",
		snippet: "$1 $2 $0",
		preview: "beqal a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "beqz",
		snippet: "$1 $0",
		preview: "beqz a(r?|num) b(r?|num)",
	},
	{
		name: "beqzal",
		snippet: "$1 $0",
		preview: "beqzal a(r?|num) b(r?|num)",
	},
	{
		name: "bge",
		snippet: "$1 $2 $0",
		preview: "bge a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bgeal",
		snippet: "$1 $2 $0",
		preview: "bgeal a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bgez",
		snippet: "$1 $0",
		preview: "bgez a(r?|num) b(r?|num)",
	},
	{
		name: "bgezal",
		snippet: "$1 $0",
		preview: "bgezal a(r?|num) b(r?|num)",
	},
	{
		name: "bgt",
		snippet: "$1 $2 $0",
		preview: "bgt a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bgtal",
		snippet: "$1 $2 $0",
		preview: "bgtal a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bgtz",
		snippet: "$1 $0",
		preview: "bgtz a(r?|num) b(r?|num)",
	},
	{
		name: "bgtzal",
		snippet: "$1 $0",
		preview: "bgtzal a(r?|num) b(r?|num)",
	},
	{
		name: "ble",
		snippet: "$1 $2 $0",
		preview: "ble a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bleal",
		snippet: "$1 $2 $0",
		preview: "bleal a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "blez",
		snippet: "$1 $0",
		preview: "blez a(r?|num) b(r?|num)",
	},
	{
		name: "blezal",
		snippet: "$1 $0",
		preview: "blezal a(r?|num) b(r?|num)",
	},
	{
		name: "blt",
		snippet: "$1 $2 $0",
		preview: "blt a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bltal",
		snippet: "$1 $2 $0",
		preview: "bltal a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bltz",
		snippet: "$1 $0",
		preview: "bltz a(r?|num) b(r?|num)",
	},
	{
		name: "bltzal",
		snippet: "$1 $0",
		preview: "bltzal a(r?|num) b(r?|num)",
	},
	{
		name: "bna",
		snippet: "$1 $2 $3 $0",
		preview: "bna a(r?|num) b(r?|num) c(r?|num) d(r?|num)",
	},
	{
		name: "bnaal",
		snippet: "$1 $2 $3 $0",
		preview: "bnaal a(r?|num) b(r?|num) c(r?|num) d(r?|num)",
	},
	{
		name: "bnan",
		snippet: "$1 $0",
		preview: "bnan a(r?|num) b(r?|num)",
	},
	{
		name: "bnaz",
		snippet: "$1 $2 $0",
		preview: "bnaz a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bnazal",
		snippet: "$1 $2 $0",
		preview: "bnazal a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bne",
		snippet: "$1 $2 $0",
		preview: "bne a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bneal",
		snippet: "$1 $2 $0",
		preview: "bneal a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "bnez",
		snippet: "$1 $0",
		preview: "bnez a(r?|num) b(r?|num)",
	},
	{
		name: "bnezal",
		snippet: "$1 $0",
		preview: "bnezal a(r?|num) b(r?|num)",
	},
	{
		name: "brap",
		snippet: "$1 $2 $3 $0",
		preview: "brap a(r?|num) b(r?|num) c(r?|num) d(r?|num)",
	},
	{
		name: "brapz",
		snippet: "$1 $2 $0",
		preview: "brapz a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "brdns",
		snippet: "${1:d0} $0",
		preview: "brdns device(d?|r?|id) a(r?|num)",
	},
	{
		name: "brdse",
		snippet: "${1:d0} $0",
		preview: "brdse device(d?|r?|id) a(r?|num)",
	},
	{
		name: "breq",
		snippet: "$1 $2 $0",
		preview: "breq a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "breqz",
		snippet: "$1 $0",
		preview: "breqz a(r?|num) b(r?|num)",
	},
	{
		name: "brge",
		snippet: "$1 $2 $0",
		preview: "brge a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "brgez",
		snippet: "$1 $0",
		preview: "brgez a(r?|num) b(r?|num)",
	},
	{
		name: "brgt",
		snippet: "$1 $2 $0",
		preview: "brgt a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "brgtz",
		snippet: "$1 $0",
		preview: "brgtz a(r?|num) b(r?|num)",
	},
	{
		name: "brle",
		snippet: "$1 $2 $0",
		preview: "brle a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "brlez",
		snippet: "$1 $0",
		preview: "brlez a(r?|num) b(r?|num)",
	},
	{
		name: "brlt",
		snippet: "$1 $2 $0",
		preview: "brlt a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "brltz",
		snippet: "$1 $0",
		preview: "brltz a(r?|num) b(r?|num)",
	},
	{
		name: "brna",
		snippet: "$1 $2 $3 $0",
		preview: "brna a(r?|num) b(r?|num) c(r?|num) d(r?|num)",
	},
	{
		name: "brnan",
		snippet: "$1 $0",
		preview: "brnan a(r?|num) b(r?|num)",
	},
	{
		name: "brnaz",
		snippet: "$1 $2 $0",
		preview: "brnaz a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "brne",
		snippet: "$1 $2 $0",
		preview: "brne a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "brnez",
		snippet: "$1 $0",
		preview: "brnez a(r?|num) b(r?|num)",
	},
	{
		name: "ceil",
		snippet: "${1:r0} $0",
		preview: "ceil r? a(r?|num)",
	},
	{
		name: "clr",
		snippet: "${0:d0}",
		preview: "clr d?",
	},
	{
		name: "clrd",
		snippet: "$0",
		preview: "clrd id(r?|num)",
	},
	{
		name: "cos",
		snippet: "${1:r0} $0",
		preview: "cos r? a(r?|num)",
	},
	{
		name: "define",
		snippet: "$1 $0",
		preview: "define str num",
	},
	{
		name: "div",
		snippet: "${1:r0} $2 $0",
		preview: "div r? a(r?|num) b(r?|num)",
	},
	{
		name: "exp",
		snippet: "${1:r0} $0",
		preview: "exp r? a(r?|num)",
	},
	{
		name: "ext",
		snippet: "${1:r0} $2 $3 $0",
		preview: "ext r? a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "floor",
		snippet: "${1:r0} $0",
		preview: "floor r? a(r?|num)",
	},
	{
		name: "get",
		snippet: "${1:r0} ${0:d0}",
		preview: "get r? device(d?|r?|id) address(r?|num)",
	},
	{
		name: "getd",
		snippet: "${1:r0} $2 $0",
		preview: "getd r? id(r?|id) address(r?|num)",
	},
	{
		name: "hcf",
		preview: "hcf",
	},
	{
		name: "ins",
		snippet: "${1:r0} $2 $3 $0",
		preview: "ins r? a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "j",
		snippet: "$0",
		preview: "j int",
	},
	{
		name: "jal",
		snippet: "$0",
		preview: "jal int",
	},
	{
		name: "jr",
		snippet: "$0",
		preview: "jr int",
	},
	{
		name: "l",
		snippet: "${1:r0} ${2:d0} $0",
		preview: "l r? device(d?|r?|id) logicType",
	},
	{
		name: "label",
		preview: "label d? str",
	},
	{
		name: "lb",
		snippet: "${1:r0} $2 $3 $0",
		preview: "lb r? deviceHash logicType batchMode",
	},
	{
		name: "lbn",
		snippet: "${1:r0} $2 $3 $4 $0",
		preview: "lbn r? deviceHash nameHash logicType batchMode",
	},
	{
		name: "lbns",
		snippet: "${1:r0} $2 $3 $4 $0",
		preview: "lbns r? deviceHash nameHash slotIndex logicSlotType batchMode",
	},
	{
		name: "lbs",
		snippet: "${1:r0} $2 $3 $4 $0",
		preview: "lbs r? deviceHash slotIndex logicSlotType batchMode",
	},
	{
		name: "ld",
		snippet: "${1:r0} $2 $0",
		preview: "ld r? id(r?|id) logicType",
	},
	{
		name: "lerp",
		snippet: "${1:r0} $2 $3 $0",
		preview: "lerp r? a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "log",
		snippet: "${1:r0} $0",
		preview: "log r? a(r?|num)",
	},
	{
		name: "lr",
		snippet: "${1:r0} ${2:d0} $3 $0",
		preview: "lr r? device(d?|r?|id) reagentMode int",
	},
	{
		name: "ls",
		snippet: "${1:r0} ${2:d0} $3 $0",
		preview: "ls r? device(d?|r?|id) slotIndex logicSlotType",
	},
	{
		name: "max",
		snippet: "${1:r0} $2 $0",
		preview: "max r? a(r?|num) b(r?|num)",
	},
	{
		name: "min",
		snippet: "${1:r0} $2 $0",
		preview: "min r? a(r?|num) b(r?|num)",
	},
	{
		name: "mod",
		snippet: "${1:r0} $2 $0",
		preview: "mod r? a(r?|num) b(r?|num)",
	},
	{
		name: "move",
		snippet: "${1:r0} $0",
		preview: "move r? a(r?|num)",
	},
	{
		name: "mul",
		snippet: "${1:r0} $2 $0",
		preview: "mul r? a(r?|num) b(r?|num)",
	},
	{
		name: "nor",
		snippet: "${1:r0} $2 $0",
		preview: "nor r? a(r?|num) b(r?|num)",
	},
	{
		name: "not",
		snippet: "${1:r0} $0",
		preview: "not r? a(r?|num)",
	},
	{
		name: "or",
		snippet: "${1:r0} $2 $0",
		preview: "or r? a(r?|num) b(r?|num)",
	},
	{
		name: "peek",
		snippet: "${0:r0}",
		preview: "peek r?",
	},
	{
		name: "poke",
		snippet: "$1 $0",
		preview: "poke address(r?|num) value(r?|num)",
	},
	{
		name: "pop",
		snippet: "${0:r0}",
		preview: "pop r?",
	},
	{
		name: "pow",
		snippet: "${1:r0} $2 $0",
		preview: "pow r? a(r?|num) b(r?|num)",
	},
	{
		name: "push",
		snippet: "$0",
		preview: "push a(r?|num)",
	},
	{
		name: "put",
		snippet: "${1:d0} $2 $0}",
		preview: "put device(d?|r?|id) address(r?|num) value(r?|num)",
	},
	{
		name: "putd",
		snippet: "$1 $2 $0",
		preview: "putd id(r?|id) address(r?|num) value(r?|num)",
	},
	{
		name: "rand",
		snippet: "${0:r0}",
		preview: "rand r?",
	},
	{
		name: "rmap",
		snippet: "${1:r0} ${2:d0} $0",
		preview: "rmap r? d? reagentHash(r?|num)",
	},
	{
		name: "round",
		snippet: "${1:r0} $0",
		preview: "round r? a(r?|num)",
	},
	{
		name: "s",
		snippet: "${1:d0} $2 ${0:r0}",
		preview: "s device(d?|r?|id) logicType r?",
	},
	{
		name: "sap",
		snippet: "${1:r0} $2 $3 $0",
		preview: "sap r? a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "sapz",
		snippet: "${1:r0} $2 $0",
		preview: "sapz r? a(r?|num) b(r?|num)",
	},
	{
		name: "sb",
		snippet: "$1 $2 ${0:r0}",
		preview: "sb deviceHash logicType r?",
	},
	{
		name: "sbn",
		snippet: "$1 $2 $3 ${0:r0}",
		preview: "sbn deviceHash nameHash logicType r?",
	},
	{
		name: "sbs",
		snippet: "$1 $2 $3 ${0:r0}",
		preview: "sbs deviceHash slotIndex logicSlotType r?",
	},
	{
		name: "sd",
		snippet: "$1 $2 ${0:r0}",
		preview: "sd id(r?|id) logicType r?",
	},
	{
		name: "sdns",
		snippet: "${1:r0} ${0:d0}",
		preview: "sdns r? device(d?|r?|id)",
	},
	{
		name: "sdse",
		snippet: "${1:r0} ${0:d0}",
		preview: "sdse r? device(d?|r?|id)",
	},
	{
		name: "select",
		snippet: "${1:r0} $2 $3 $0",
		preview: "select r? a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "seq",
		snippet: "${1:r0} $2 $0",
		preview: "seq r? a(r?|num) b(r?|num)",
	},
	{
		name: "seqz",
		snippet: "${1:r0} $0",
		preview: "seqz r? a(r?|num)",
	},
	{
		name: "sge",
		snippet: "${1:r0} $2 $0",
		preview: "sge r? a(r?|num) b(r?|num)",
	},
	{
		name: "sgez",
		snippet: "${1:r0} $0",
		preview: "sgez r? a(r?|num)",
	},
	{
		name: "sgt",
		snippet: "${1:r0} $2 $0",
		preview: "sgt r? a(r?|num) b(r?|num)",
	},
	{
		name: "sgtz",
		snippet: "${1:r0} $0",
		preview: "sgtz r? a(r?|num)",
	},
	{
		name: "sin",
		snippet: "${1:r0} $0",
		preview: "sin r? a(r?|num)",
	},
	{
		name: "sla",
		snippet: "${1:r0} $2 $0",
		preview: "sla r? a(r?|num) b(r?|num)",
	},
	{
		name: "sle",
		snippet: "${1:r0} $2 $0",
		preview: "sle r? a(r?|num) b(r?|num)",
	},
	{
		name: "sleep",
		snippet: "$0",
		preview: "sleep a(r?|num)",
	},
	{
		name: "slez",
		snippet: "${1:r0} $0",
		preview: "slez r? a(r?|num)",
	},
	{
		name: "sll",
		snippet: "${1:r0} $2 $0",
		preview: "sll r? a(r?|num) b(r?|num)",
	},
	{
		name: "slt",
		snippet: "${1:r0} $2 $0",
		preview: "slt r? a(r?|num) b(r?|num)",
	},
	{
		name: "sltz",
		snippet: "${1:r0} $0",
		preview: "sltz r? a(r?|num)",
	},
	{
		name: "sna",
		snippet: "${1:r0} $2 $3 $0",
		preview: "sna r? a(r?|num) b(r?|num) c(r?|num)",
	},
	{
		name: "snan",
		snippet: "${1:r0} $0",
		preview: "snan r? a(r?|num)",
	},
	{
		name: "snanz",
		snippet: "${1:r0} $0",
		preview: "snanz r? a(r?|num)",
	},
	{
		name: "snaz",
		snippet: "${1:r0} $2 $0",
		preview: "snaz r? a(r?|num) b(r?|num)",
	},
	{
		name: "sne",
		snippet: "${1:r0} $2 $0",
		preview: "sne r? a(r?|num) b(r?|num)",
	},
	{
		name: "snez",
		snippet: "${1:r0} $0",
		preview: "snez r? a(r?|num)",
	},
	{
		name: "sqrt",
		snippet: "${1:r0} $0",
		preview: "sqrt r? a(r?|num)",
	},
	{
		name: "sra",
		snippet: "${1:r0} $2 $0",
		preview: "sra r? a(r?|num) b(r?|num)",
	},
	{
		name: "srl",
		snippet: "${1:r0} $2 $0",
		preview: "srl r? a(r?|num) b(r?|num)",
	},
	{
		name: "ss",
		snippet: "${1:d0} $2 $3 ${0:r0}",
		preview: "ss device(d?|r?|id) slotIndex logicSlotType r?",
	},
	{
		name: "sub",
		snippet: "${1:r0} $2 $0",
		preview: "sub r? a(r?|num) b(r?|num)",
	},
	{
		name: "tan",
		snippet: "${1:r0} $0",
		preview: "tan r? a(r?|num)",
	},
	{
		name: "trunc",
		snippet: "${1:r0} $0",
		preview: "trunc r? a(r?|num)",
	},
	{
		name: "xor",
		snippet: "${1:r0} $2 $0",
		preview: "xor r? a(r?|num) b(r?|num)",
	},
	{
		name: "yield",
		preview: "yield",
	},
] satisfies {
	name: string
	snippet?: string
	preview: string
	deprecated?: boolean
}[] as {
	name: string
	snippet?: string
	preview: string
	deprecated?: boolean
}[]
