// This file is auto-generated by tools/updateData/index.ts
import type { nestedData } from "."
export default {
	LogicBatchMethod: {
		Average: {
			literal: "LogicBatchMethod.Average",
			value: 0,
			kind: 1,
		},
		Maximum: {
			literal: "LogicBatchMethod.Maximum",
			value: 3,
			kind: 1,
		},
		Minimum: {
			literal: "LogicBatchMethod.Minimum",
			value: 2,
			kind: 1,
		},
		Sum: {
			literal: "LogicBatchMethod.Sum",
			value: 1,
			kind: 1,
		},
	},
	LogicReagentMode: {
		Contents: {
			literal: "LogicReagentMode.Contents",
			value: 0,
			kind: 1,
		},
		Recipe: {
			literal: "LogicReagentMode.Recipe",
			value: 2,
			kind: 1,
		},
		Required: {
			literal: "LogicReagentMode.Required",
			value: 1,
			kind: 1,
		},
		TotalContents: {
			literal: "LogicReagentMode.TotalContents",
			value: 3,
			kind: 1,
		},
	},
	LogicSlotType: {
		Charge: {
			literal: "LogicSlotType.Charge",
			value: 10,
			kind: 1,
		},
		ChargeRatio: {
			literal: "LogicSlotType.ChargeRatio",
			value: 11,
			kind: 1,
		},
		Class: {
			literal: "LogicSlotType.Class",
			value: 12,
			kind: 1,
		},
		Damage: {
			literal: "LogicSlotType.Damage",
			value: 4,
			kind: 1,
		},
		Efficiency: {
			literal: "LogicSlotType.Efficiency",
			value: 5,
			kind: 1,
		},
		FilterType: {
			literal: "LogicSlotType.FilterType",
			value: 25,
			kind: 1,
		},
		Growth: {
			literal: "LogicSlotType.Growth",
			value: 7,
			kind: 1,
		},
		HarvestedHash: {
			literal: "LogicSlotType.HarvestedHash",
			value: 27,
			kind: 1,
		},
		Health: {
			literal: "LogicSlotType.Health",
			value: 6,
			kind: 1,
		},
		LineNumber: {
			literal: "LogicSlotType.LineNumber",
			value: 19,
			kind: 1,
		},
		Lock: {
			literal: "LogicSlotType.Lock",
			value: 23,
			kind: 1,
		},
		Mature: {
			literal: "LogicSlotType.Mature",
			value: 16,
			kind: 1,
		},
		MaturityRatio: {
			literal: "LogicSlotType.MaturityRatio",
			value: 29,
			kind: 1,
		},
		MaxQuantity: {
			literal: "LogicSlotType.MaxQuantity",
			value: 15,
			kind: 1,
		},
		Mode: {
			literal: "LogicSlotType.Mode",
			value: 28,
			kind: 1,
		},
		None: {
			literal: "LogicSlotType.None",
			value: 0,
			kind: 1,
		},
		OccupantHash: {
			literal: "LogicSlotType.OccupantHash",
			value: 2,
			kind: 1,
		},
		Occupied: {
			literal: "LogicSlotType.Occupied",
			value: 1,
			kind: 1,
		},
		On: {
			literal: "LogicSlotType.On",
			value: 22,
			kind: 1,
		},
		Open: {
			literal: "LogicSlotType.Open",
			value: 21,
			kind: 1,
		},
		PrefabHash: {
			literal: "LogicSlotType.PrefabHash",
			value: 17,
			kind: 1,
		},
		Pressure: {
			literal: "LogicSlotType.Pressure",
			value: 8,
			kind: 1,
		},
		PressureAir: {
			literal: "LogicSlotType.PressureAir",
			value: 14,
			kind: 1,
		},
		PressureWaste: {
			literal: "LogicSlotType.PressureWaste",
			value: 13,
			kind: 1,
		},
		Quantity: {
			literal: "LogicSlotType.Quantity",
			value: 3,
			kind: 1,
		},
		ReferenceId: {
			literal: "LogicSlotType.ReferenceId",
			value: 26,
			kind: 1,
		},
		Seeding: {
			literal: "LogicSlotType.Seeding",
			value: 18,
			kind: 1,
		},
		SeedingRatio: {
			literal: "LogicSlotType.SeedingRatio",
			value: 30,
			kind: 1,
		},
		SortingClass: {
			literal: "LogicSlotType.SortingClass",
			value: 24,
			kind: 1,
		},
		Temperature: {
			literal: "LogicSlotType.Temperature",
			value: 9,
			kind: 1,
		},
		Volume: {
			literal: "LogicSlotType.Volume",
			value: 20,
			kind: 1,
		},
	},
	LogicType: {
		Acceleration: {
			literal: "LogicType.Acceleration",
			value: 216,
			kind: 1,
		},
		Activate: {
			literal: "LogicType.Activate",
			value: 9,
			kind: 1,
		},
		AirRelease: {
			literal: "LogicType.AirRelease",
			value: 75,
			kind: 1,
		},
		AlignmentError: {
			literal: "LogicType.AlignmentError",
			value: 243,
			kind: 1,
		},
		Altitude: {
			literal: "LogicType.Altitude",
			value: 269,
			kind: 1,
		},
		Apex: {
			literal: "LogicType.Apex",
			value: 238,
			kind: 1,
		},
		AutoLand: {
			literal: "LogicType.AutoLand",
			value: 226,
			kind: 1,
		},
		AutoShutOff: {
			literal: "LogicType.AutoShutOff",
			value: 218,
			kind: 1,
		},
		BestContactFilter: {
			literal: "LogicType.BestContactFilter",
			value: 267,
			kind: 1,
		},
		Bpm: {
			literal: "LogicType.Bpm",
			value: 103,
			kind: 1,
		},
		BurnTimeRemaining: {
			literal: "LogicType.BurnTimeRemaining",
			value: 225,
			kind: 1,
		},
		CelestialHash: {
			literal: "LogicType.CelestialHash",
			value: 242,
			kind: 1,
		},
		CelestialParentHash: {
			literal: "LogicType.CelestialParentHash",
			value: 250,
			kind: 1,
		},
		Channel0: {
			literal: "LogicType.Channel0",
			value: 165,
			kind: 1,
		},
		Channel1: {
			literal: "LogicType.Channel1",
			value: 166,
			kind: 1,
		},
		Channel2: {
			literal: "LogicType.Channel2",
			value: 167,
			kind: 1,
		},
		Channel3: {
			literal: "LogicType.Channel3",
			value: 168,
			kind: 1,
		},
		Channel4: {
			literal: "LogicType.Channel4",
			value: 169,
			kind: 1,
		},
		Channel5: {
			literal: "LogicType.Channel5",
			value: 170,
			kind: 1,
		},
		Channel6: {
			literal: "LogicType.Channel6",
			value: 171,
			kind: 1,
		},
		Channel7: {
			literal: "LogicType.Channel7",
			value: 172,
			kind: 1,
		},
		Charge: {
			literal: "LogicType.Charge",
			value: 11,
			kind: 1,
		},
		Chart: {
			literal: "LogicType.Chart",
			value: 256,
			kind: 1,
		},
		ChartedNavPoints: {
			literal: "LogicType.ChartedNavPoints",
			value: 259,
			kind: 1,
		},
		ClearMemory: {
			literal: "LogicType.ClearMemory",
			value: 62,
			kind: 1,
		},
		CollectableGoods: {
			literal: "LogicType.CollectableGoods",
			value: 101,
			kind: 1,
		},
		Color: {
			literal: "LogicType.Color",
			value: 38,
			kind: 1,
		},
		Combustion: {
			literal: "LogicType.Combustion",
			value: 98,
			kind: 1,
		},
		CombustionInput: {
			literal: "LogicType.CombustionInput",
			value: 146,
			kind: 1,
		},
		CombustionInput2: {
			literal: "LogicType.CombustionInput2",
			value: 147,
			kind: 1,
		},
		CombustionLimiter: {
			literal: "LogicType.CombustionLimiter",
			value: 153,
			kind: 1,
		},
		CombustionOutput: {
			literal: "LogicType.CombustionOutput",
			value: 148,
			kind: 1,
		},
		CombustionOutput2: {
			literal: "LogicType.CombustionOutput2",
			value: 149,
			kind: 1,
		},
		CompletionRatio: {
			literal: "LogicType.CompletionRatio",
			value: 61,
			kind: 1,
		},
		ContactTypeId: {
			literal: "LogicType.ContactTypeId",
			value: 198,
			kind: 1,
		},
		CurrentCode: {
			literal: "LogicType.CurrentCode",
			value: 261,
			kind: 1,
		},
		CurrentResearchPodType: {
			literal: "LogicType.CurrentResearchPodType",
			value: 93,
			kind: 1,
		},
		Density: {
			literal: "LogicType.Density",
			value: 262,
			kind: 1,
		},
		DerivativeGain: {
			literal: "LogicType.DerivativeGain",
			value: 276,
			kind: 1,
		},
		DestinationCode: {
			literal: "LogicType.DestinationCode",
			value: 215,
			kind: 1,
		},
		Discover: {
			literal: "LogicType.Discover",
			value: 255,
			kind: 1,
		},
		DistanceAu: {
			literal: "LogicType.DistanceAu",
			value: 244,
			kind: 1,
		},
		DistanceKm: {
			literal: "LogicType.DistanceKm",
			value: 249,
			kind: 1,
		},
		DrillCondition: {
			literal: "LogicType.DrillCondition",
			value: 240,
			kind: 1,
		},
		DryMass: {
			literal: "LogicType.DryMass",
			value: 220,
			kind: 1,
		},
		Eccentricity: {
			literal: "LogicType.Eccentricity",
			value: 247,
			kind: 1,
		},
		ElevatorLevel: {
			literal: "LogicType.ElevatorLevel",
			value: 40,
			kind: 1,
		},
		ElevatorSpeed: {
			literal: "LogicType.ElevatorSpeed",
			value: 39,
			kind: 1,
		},
		EntityState: {
			literal: "LogicType.EntityState",
			value: 239,
			kind: 1,
		},
		EnvironmentEfficiency: {
			literal: "LogicType.EnvironmentEfficiency",
			value: 104,
			kind: 1,
		},
		Error: {
			literal: "LogicType.Error",
			value: 4,
			kind: 1,
		},
		ExhaustVelocity: {
			literal: "LogicType.ExhaustVelocity",
			value: 235,
			kind: 1,
		},
		ExportCount: {
			literal: "LogicType.ExportCount",
			value: 63,
			kind: 1,
		},
		ExportQuantity: {
			literal: "LogicType.ExportQuantity",
			value: 31,
			deprecated: true,
			kind: 1,
		},
		ExportSlotHash: {
			literal: "LogicType.ExportSlotHash",
			value: 42,
			deprecated: true,
			kind: 1,
		},
		ExportSlotOccupant: {
			literal: "LogicType.ExportSlotOccupant",
			value: 32,
			deprecated: true,
			kind: 1,
		},
		Extended: {
			literal: "LogicType.Extended",
			value: 272,
			kind: 1,
		},
		Filtration: {
			literal: "LogicType.Filtration",
			value: 74,
			kind: 1,
		},
		FlightControlRule: {
			literal: "LogicType.FlightControlRule",
			value: 236,
			kind: 1,
		},
		Flush: {
			literal: "LogicType.Flush",
			value: 174,
			kind: 1,
		},
		ForceWrite: {
			literal: "LogicType.ForceWrite",
			value: 85,
			kind: 1,
		},
		ForwardX: {
			literal: "LogicType.ForwardX",
			value: 227,
			kind: 1,
		},
		ForwardY: {
			literal: "LogicType.ForwardY",
			value: 228,
			kind: 1,
		},
		ForwardZ: {
			literal: "LogicType.ForwardZ",
			value: 229,
			kind: 1,
		},
		Fuel: {
			literal: "LogicType.Fuel",
			value: 99,
			kind: 1,
		},
		Harvest: {
			literal: "LogicType.Harvest",
			value: 69,
			kind: 1,
		},
		Horizontal: {
			literal: "LogicType.Horizontal",
			value: 20,
			kind: 1,
		},
		HorizontalRatio: {
			literal: "LogicType.HorizontalRatio",
			value: 34,
			kind: 1,
		},
		Idle: {
			literal: "LogicType.Idle",
			value: 37,
			kind: 1,
		},
		ImportCount: {
			literal: "LogicType.ImportCount",
			value: 64,
			kind: 1,
		},
		ImportQuantity: {
			literal: "LogicType.ImportQuantity",
			value: 29,
			deprecated: true,
			kind: 1,
		},
		ImportSlotHash: {
			literal: "LogicType.ImportSlotHash",
			value: 43,
			deprecated: true,
			kind: 1,
		},
		ImportSlotOccupant: {
			literal: "LogicType.ImportSlotOccupant",
			value: 30,
			deprecated: true,
			kind: 1,
		},
		Inclination: {
			literal: "LogicType.Inclination",
			value: 246,
			kind: 1,
		},
		Index: {
			literal: "LogicType.Index",
			value: 241,
			kind: 1,
		},
		IntegralGain: {
			literal: "LogicType.IntegralGain",
			value: 275,
			kind: 1,
		},
		InterrogationProgress: {
			literal: "LogicType.InterrogationProgress",
			value: 157,
			kind: 1,
		},
		LineNumber: {
			literal: "LogicType.LineNumber",
			value: 173,
			kind: 1,
		},
		Lock: {
			literal: "LogicType.Lock",
			value: 10,
			kind: 1,
		},
		ManualResearchRequiredPod: {
			literal: "LogicType.ManualResearchRequiredPod",
			value: 94,
			kind: 1,
		},
		Mass: {
			literal: "LogicType.Mass",
			value: 219,
			kind: 1,
		},
		Maximum: {
			literal: "LogicType.Maximum",
			value: 23,
			kind: 1,
		},
		MineablesInQueue: {
			literal: "LogicType.MineablesInQueue",
			value: 96,
			kind: 1,
		},
		MineablesInVicinity: {
			literal: "LogicType.MineablesInVicinity",
			value: 95,
			kind: 1,
		},
		MinedQuantity: {
			literal: "LogicType.MinedQuantity",
			value: 266,
			kind: 1,
		},
		Minimum: {
			literal: "LogicType.Minimum",
			value: 277,
			kind: 1,
		},
		MinimumWattsToContact: {
			literal: "LogicType.MinimumWattsToContact",
			value: 163,
			kind: 1,
		},
		Mode: {
			literal: "LogicType.Mode",
			value: 3,
			kind: 1,
		},
		NameHash: {
			literal: "LogicType.NameHash",
			value: 268,
			kind: 1,
		},
		NavPoints: {
			literal: "LogicType.NavPoints",
			value: 258,
			kind: 1,
		},
		NetworkFault: {
			literal: "LogicType.NetworkFault",
			value: 273,
			kind: 1,
		},
		NextWeatherEventTime: {
			literal: "LogicType.NextWeatherEventTime",
			value: 97,
			kind: 1,
		},
		None: {
			literal: "LogicType.None",
			value: 0,
			deprecated: true,
			kind: 1,
		},
		On: {
			literal: "LogicType.On",
			value: 28,
			kind: 1,
		},
		Open: {
			literal: "LogicType.Open",
			value: 2,
			kind: 1,
		},
		OperationalTemperatureEfficiency: {
			literal: "LogicType.OperationalTemperatureEfficiency",
			value: 150,
			kind: 1,
		},
		OrbitPeriod: {
			literal: "LogicType.OrbitPeriod",
			value: 245,
			kind: 1,
		},
		Orientation: {
			literal: "LogicType.Orientation",
			value: 230,
			kind: 1,
		},
		Output: {
			literal: "LogicType.Output",
			value: 70,
			kind: 1,
		},
		PassedMoles: {
			literal: "LogicType.PassedMoles",
			value: 234,
			kind: 1,
		},
		Plant: {
			literal: "LogicType.Plant",
			value: 68,
			kind: 1,
		},
		PlantEfficiency1: {
			literal: "LogicType.PlantEfficiency1",
			value: 52,
			deprecated: true,
			kind: 1,
		},
		PlantEfficiency2: {
			literal: "LogicType.PlantEfficiency2",
			value: 53,
			deprecated: true,
			kind: 1,
		},
		PlantEfficiency3: {
			literal: "LogicType.PlantEfficiency3",
			value: 54,
			deprecated: true,
			kind: 1,
		},
		PlantEfficiency4: {
			literal: "LogicType.PlantEfficiency4",
			value: 55,
			deprecated: true,
			kind: 1,
		},
		PlantGrowth1: {
			literal: "LogicType.PlantGrowth1",
			value: 48,
			deprecated: true,
			kind: 1,
		},
		PlantGrowth2: {
			literal: "LogicType.PlantGrowth2",
			value: 49,
			deprecated: true,
			kind: 1,
		},
		PlantGrowth3: {
			literal: "LogicType.PlantGrowth3",
			value: 50,
			deprecated: true,
			kind: 1,
		},
		PlantGrowth4: {
			literal: "LogicType.PlantGrowth4",
			value: 51,
			deprecated: true,
			kind: 1,
		},
		PlantHash1: {
			literal: "LogicType.PlantHash1",
			value: 56,
			deprecated: true,
			kind: 1,
		},
		PlantHash2: {
			literal: "LogicType.PlantHash2",
			value: 57,
			deprecated: true,
			kind: 1,
		},
		PlantHash3: {
			literal: "LogicType.PlantHash3",
			value: 58,
			deprecated: true,
			kind: 1,
		},
		PlantHash4: {
			literal: "LogicType.PlantHash4",
			value: 59,
			deprecated: true,
			kind: 1,
		},
		PlantHealth1: {
			literal: "LogicType.PlantHealth1",
			value: 44,
			deprecated: true,
			kind: 1,
		},
		PlantHealth2: {
			literal: "LogicType.PlantHealth2",
			value: 45,
			deprecated: true,
			kind: 1,
		},
		PlantHealth3: {
			literal: "LogicType.PlantHealth3",
			value: 46,
			deprecated: true,
			kind: 1,
		},
		PlantHealth4: {
			literal: "LogicType.PlantHealth4",
			value: 47,
			deprecated: true,
			kind: 1,
		},
		PositionX: {
			literal: "LogicType.PositionX",
			value: 76,
			kind: 1,
		},
		PositionY: {
			literal: "LogicType.PositionY",
			value: 77,
			kind: 1,
		},
		PositionZ: {
			literal: "LogicType.PositionZ",
			value: 78,
			kind: 1,
		},
		Power: {
			literal: "LogicType.Power",
			value: 1,
			kind: 1,
		},
		PowerActual: {
			literal: "LogicType.PowerActual",
			value: 26,
			kind: 1,
		},
		PowerGeneration: {
			literal: "LogicType.PowerGeneration",
			value: 65,
			kind: 1,
		},
		PowerPotential: {
			literal: "LogicType.PowerPotential",
			value: 25,
			kind: 1,
		},
		PowerRequired: {
			literal: "LogicType.PowerRequired",
			value: 36,
			kind: 1,
		},
		PrefabHash: {
			literal: "LogicType.PrefabHash",
			value: 84,
			kind: 1,
		},
		Pressure: {
			literal: "LogicType.Pressure",
			value: 5,
			kind: 1,
		},
		PressureEfficiency: {
			literal: "LogicType.PressureEfficiency",
			value: 152,
			kind: 1,
		},
		PressureExternal: {
			literal: "LogicType.PressureExternal",
			value: 7,
			kind: 1,
		},
		PressureInput: {
			literal: "LogicType.PressureInput",
			value: 106,
			kind: 1,
		},
		PressureInput2: {
			literal: "LogicType.PressureInput2",
			value: 116,
			kind: 1,
		},
		PressureInternal: {
			literal: "LogicType.PressureInternal",
			value: 8,
			kind: 1,
		},
		PressureOutput: {
			literal: "LogicType.PressureOutput",
			value: 126,
			kind: 1,
		},
		PressureOutput2: {
			literal: "LogicType.PressureOutput2",
			value: 136,
			kind: 1,
		},
		PressureSetting: {
			literal: "LogicType.PressureSetting",
			value: 71,
			kind: 1,
		},
		Progress: {
			literal: "LogicType.Progress",
			value: 214,
			kind: 1,
		},
		ProportionalGain: {
			literal: "LogicType.ProportionalGain",
			value: 274,
			kind: 1,
		},
		Quantity: {
			literal: "LogicType.Quantity",
			value: 27,
			kind: 1,
		},
		Ratio: {
			literal: "LogicType.Ratio",
			value: 24,
			kind: 1,
		},
		RatioCarbonDioxide: {
			literal: "LogicType.RatioCarbonDioxide",
			value: 15,
			kind: 1,
		},
		RatioCarbonDioxideInput: {
			literal: "LogicType.RatioCarbonDioxideInput",
			value: 109,
			kind: 1,
		},
		RatioCarbonDioxideInput2: {
			literal: "LogicType.RatioCarbonDioxideInput2",
			value: 119,
			kind: 1,
		},
		RatioCarbonDioxideOutput: {
			literal: "LogicType.RatioCarbonDioxideOutput",
			value: 129,
			kind: 1,
		},
		RatioCarbonDioxideOutput2: {
			literal: "LogicType.RatioCarbonDioxideOutput2",
			value: 139,
			kind: 1,
		},
		RatioHydrogen: {
			literal: "LogicType.RatioHydrogen",
			value: 252,
			kind: 1,
		},
		RatioLiquidCarbonDioxide: {
			literal: "LogicType.RatioLiquidCarbonDioxide",
			value: 199,
			kind: 1,
		},
		RatioLiquidCarbonDioxideInput: {
			literal: "LogicType.RatioLiquidCarbonDioxideInput",
			value: 200,
			kind: 1,
		},
		RatioLiquidCarbonDioxideInput2: {
			literal: "LogicType.RatioLiquidCarbonDioxideInput2",
			value: 201,
			kind: 1,
		},
		RatioLiquidCarbonDioxideOutput: {
			literal: "LogicType.RatioLiquidCarbonDioxideOutput",
			value: 202,
			kind: 1,
		},
		RatioLiquidCarbonDioxideOutput2: {
			literal: "LogicType.RatioLiquidCarbonDioxideOutput2",
			value: 203,
			kind: 1,
		},
		RatioLiquidHydrogen: {
			literal: "LogicType.RatioLiquidHydrogen",
			value: 253,
			kind: 1,
		},
		RatioLiquidNitrogen: {
			literal: "LogicType.RatioLiquidNitrogen",
			value: 177,
			kind: 1,
		},
		RatioLiquidNitrogenInput: {
			literal: "LogicType.RatioLiquidNitrogenInput",
			value: 178,
			kind: 1,
		},
		RatioLiquidNitrogenInput2: {
			literal: "LogicType.RatioLiquidNitrogenInput2",
			value: 179,
			kind: 1,
		},
		RatioLiquidNitrogenOutput: {
			literal: "LogicType.RatioLiquidNitrogenOutput",
			value: 180,
			kind: 1,
		},
		RatioLiquidNitrogenOutput2: {
			literal: "LogicType.RatioLiquidNitrogenOutput2",
			value: 181,
			kind: 1,
		},
		RatioLiquidNitrousOxide: {
			literal: "LogicType.RatioLiquidNitrousOxide",
			value: 209,
			kind: 1,
		},
		RatioLiquidNitrousOxideInput: {
			literal: "LogicType.RatioLiquidNitrousOxideInput",
			value: 210,
			kind: 1,
		},
		RatioLiquidNitrousOxideInput2: {
			literal: "LogicType.RatioLiquidNitrousOxideInput2",
			value: 211,
			kind: 1,
		},
		RatioLiquidNitrousOxideOutput: {
			literal: "LogicType.RatioLiquidNitrousOxideOutput",
			value: 212,
			kind: 1,
		},
		RatioLiquidNitrousOxideOutput2: {
			literal: "LogicType.RatioLiquidNitrousOxideOutput2",
			value: 213,
			kind: 1,
		},
		RatioLiquidOxygen: {
			literal: "LogicType.RatioLiquidOxygen",
			value: 183,
			kind: 1,
		},
		RatioLiquidOxygenInput: {
			literal: "LogicType.RatioLiquidOxygenInput",
			value: 184,
			kind: 1,
		},
		RatioLiquidOxygenInput2: {
			literal: "LogicType.RatioLiquidOxygenInput2",
			value: 185,
			kind: 1,
		},
		RatioLiquidOxygenOutput: {
			literal: "LogicType.RatioLiquidOxygenOutput",
			value: 186,
			kind: 1,
		},
		RatioLiquidOxygenOutput2: {
			literal: "LogicType.RatioLiquidOxygenOutput2",
			value: 187,
			kind: 1,
		},
		RatioLiquidPollutant: {
			literal: "LogicType.RatioLiquidPollutant",
			value: 204,
			kind: 1,
		},
		RatioLiquidPollutantInput: {
			literal: "LogicType.RatioLiquidPollutantInput",
			value: 205,
			kind: 1,
		},
		RatioLiquidPollutantInput2: {
			literal: "LogicType.RatioLiquidPollutantInput2",
			value: 206,
			kind: 1,
		},
		RatioLiquidPollutantOutput: {
			literal: "LogicType.RatioLiquidPollutantOutput",
			value: 207,
			kind: 1,
		},
		RatioLiquidPollutantOutput2: {
			literal: "LogicType.RatioLiquidPollutantOutput2",
			value: 208,
			kind: 1,
		},
		RatioLiquidVolatiles: {
			literal: "LogicType.RatioLiquidVolatiles",
			value: 188,
			kind: 1,
		},
		RatioLiquidVolatilesInput: {
			literal: "LogicType.RatioLiquidVolatilesInput",
			value: 189,
			kind: 1,
		},
		RatioLiquidVolatilesInput2: {
			literal: "LogicType.RatioLiquidVolatilesInput2",
			value: 190,
			kind: 1,
		},
		RatioLiquidVolatilesOutput: {
			literal: "LogicType.RatioLiquidVolatilesOutput",
			value: 191,
			kind: 1,
		},
		RatioLiquidVolatilesOutput2: {
			literal: "LogicType.RatioLiquidVolatilesOutput2",
			value: 192,
			kind: 1,
		},
		RatioNitrogen: {
			literal: "LogicType.RatioNitrogen",
			value: 16,
			kind: 1,
		},
		RatioNitrogenInput: {
			literal: "LogicType.RatioNitrogenInput",
			value: 110,
			kind: 1,
		},
		RatioNitrogenInput2: {
			literal: "LogicType.RatioNitrogenInput2",
			value: 120,
			kind: 1,
		},
		RatioNitrogenOutput: {
			literal: "LogicType.RatioNitrogenOutput",
			value: 130,
			kind: 1,
		},
		RatioNitrogenOutput2: {
			literal: "LogicType.RatioNitrogenOutput2",
			value: 140,
			kind: 1,
		},
		RatioNitrousOxide: {
			literal: "LogicType.RatioNitrousOxide",
			value: 83,
			kind: 1,
		},
		RatioNitrousOxideInput: {
			literal: "LogicType.RatioNitrousOxideInput",
			value: 114,
			kind: 1,
		},
		RatioNitrousOxideInput2: {
			literal: "LogicType.RatioNitrousOxideInput2",
			value: 124,
			kind: 1,
		},
		RatioNitrousOxideOutput: {
			literal: "LogicType.RatioNitrousOxideOutput",
			value: 134,
			kind: 1,
		},
		RatioNitrousOxideOutput2: {
			literal: "LogicType.RatioNitrousOxideOutput2",
			value: 144,
			kind: 1,
		},
		RatioOxygen: {
			literal: "LogicType.RatioOxygen",
			value: 14,
			kind: 1,
		},
		RatioOxygenInput: {
			literal: "LogicType.RatioOxygenInput",
			value: 108,
			kind: 1,
		},
		RatioOxygenInput2: {
			literal: "LogicType.RatioOxygenInput2",
			value: 118,
			kind: 1,
		},
		RatioOxygenOutput: {
			literal: "LogicType.RatioOxygenOutput",
			value: 128,
			kind: 1,
		},
		RatioOxygenOutput2: {
			literal: "LogicType.RatioOxygenOutput2",
			value: 138,
			kind: 1,
		},
		RatioPollutant: {
			literal: "LogicType.RatioPollutant",
			value: 17,
			kind: 1,
		},
		RatioPollutantInput: {
			literal: "LogicType.RatioPollutantInput",
			value: 111,
			kind: 1,
		},
		RatioPollutantInput2: {
			literal: "LogicType.RatioPollutantInput2",
			value: 121,
			kind: 1,
		},
		RatioPollutantOutput: {
			literal: "LogicType.RatioPollutantOutput",
			value: 131,
			kind: 1,
		},
		RatioPollutantOutput2: {
			literal: "LogicType.RatioPollutantOutput2",
			value: 141,
			kind: 1,
		},
		RatioPollutedWater: {
			literal: "LogicType.RatioPollutedWater",
			value: 254,
			kind: 1,
		},
		RatioSteam: {
			literal: "LogicType.RatioSteam",
			value: 193,
			kind: 1,
		},
		RatioSteamInput: {
			literal: "LogicType.RatioSteamInput",
			value: 194,
			kind: 1,
		},
		RatioSteamInput2: {
			literal: "LogicType.RatioSteamInput2",
			value: 195,
			kind: 1,
		},
		RatioSteamOutput: {
			literal: "LogicType.RatioSteamOutput",
			value: 196,
			kind: 1,
		},
		RatioSteamOutput2: {
			literal: "LogicType.RatioSteamOutput2",
			value: 197,
			kind: 1,
		},
		RatioVolatiles: {
			literal: "LogicType.RatioVolatiles",
			value: 18,
			kind: 1,
		},
		RatioVolatilesInput: {
			literal: "LogicType.RatioVolatilesInput",
			value: 112,
			kind: 1,
		},
		RatioVolatilesInput2: {
			literal: "LogicType.RatioVolatilesInput2",
			value: 122,
			kind: 1,
		},
		RatioVolatilesOutput: {
			literal: "LogicType.RatioVolatilesOutput",
			value: 132,
			kind: 1,
		},
		RatioVolatilesOutput2: {
			literal: "LogicType.RatioVolatilesOutput2",
			value: 142,
			kind: 1,
		},
		RatioWater: {
			literal: "LogicType.RatioWater",
			value: 19,
			kind: 1,
		},
		RatioWaterInput: {
			literal: "LogicType.RatioWaterInput",
			value: 113,
			kind: 1,
		},
		RatioWaterInput2: {
			literal: "LogicType.RatioWaterInput2",
			value: 123,
			kind: 1,
		},
		RatioWaterOutput: {
			literal: "LogicType.RatioWaterOutput",
			value: 133,
			kind: 1,
		},
		RatioWaterOutput2: {
			literal: "LogicType.RatioWaterOutput2",
			value: 143,
			kind: 1,
		},
		ReEntryAltitude: {
			literal: "LogicType.ReEntryAltitude",
			value: 237,
			kind: 1,
		},
		Reagents: {
			literal: "LogicType.Reagents",
			value: 13,
			kind: 1,
		},
		RecipeHash: {
			literal: "LogicType.RecipeHash",
			value: 41,
			kind: 1,
		},
		ReferenceId: {
			literal: "LogicType.ReferenceId",
			value: 217,
			kind: 1,
		},
		RequestHash: {
			literal: "LogicType.RequestHash",
			value: 60,
			kind: 1,
		},
		RequiredPower: {
			literal: "LogicType.RequiredPower",
			value: 33,
			kind: 1,
		},
		Reset: {
			literal: "LogicType.Reset",
			value: 279,
			kind: 1,
		},
		ReturnFuelCost: {
			literal: "LogicType.ReturnFuelCost",
			value: 100,
			kind: 1,
		},
		Richness: {
			literal: "LogicType.Richness",
			value: 263,
			kind: 1,
		},
		Rpm: {
			literal: "LogicType.Rpm",
			value: 155,
			kind: 1,
		},
		SemiMajorAxis: {
			literal: "LogicType.SemiMajorAxis",
			value: 248,
			kind: 1,
		},
		Setpoint: {
			literal: "LogicType.Setpoint",
			value: 278,
			kind: 1,
		},
		Setting: {
			literal: "LogicType.Setting",
			value: 12,
			kind: 1,
		},
		SettingInput: {
			literal: "LogicType.SettingInput",
			value: 91,
			kind: 1,
		},
		SettingOutput: {
			literal: "LogicType.SettingOutput",
			value: 92,
			kind: 1,
		},
		SignalID: {
			literal: "LogicType.SignalID",
			value: 87,
			kind: 1,
		},
		SignalStrength: {
			literal: "LogicType.SignalStrength",
			value: 86,
			kind: 1,
		},
		Sites: {
			literal: "LogicType.Sites",
			value: 260,
			kind: 1,
		},
		Size: {
			literal: "LogicType.Size",
			value: 264,
			kind: 1,
		},
		SizeX: {
			literal: "LogicType.SizeX",
			value: 160,
			kind: 1,
		},
		SizeY: {
			literal: "LogicType.SizeY",
			value: 161,
			kind: 1,
		},
		SizeZ: {
			literal: "LogicType.SizeZ",
			value: 162,
			kind: 1,
		},
		SolarAngle: {
			literal: "LogicType.SolarAngle",
			value: 22,
			kind: 1,
		},
		SolarIrradiance: {
			literal: "LogicType.SolarIrradiance",
			value: 176,
			kind: 1,
		},
		SoundAlert: {
			literal: "LogicType.SoundAlert",
			value: 175,
			kind: 1,
		},
		StackSize: {
			literal: "LogicType.StackSize",
			value: 280,
			kind: 1,
		},
		Stress: {
			literal: "LogicType.Stress",
			value: 156,
			kind: 1,
		},
		Survey: {
			literal: "LogicType.Survey",
			value: 257,
			kind: 1,
		},
		TargetPadIndex: {
			literal: "LogicType.TargetPadIndex",
			value: 158,
			kind: 1,
		},
		TargetPrefabHash: {
			literal: "LogicType.TargetPrefabHash",
			value: 271,
			kind: 1,
		},
		TargetSlotIndex: {
			literal: "LogicType.TargetSlotIndex",
			value: 270,
			kind: 1,
		},
		TargetX: {
			literal: "LogicType.TargetX",
			value: 88,
			kind: 1,
		},
		TargetY: {
			literal: "LogicType.TargetY",
			value: 89,
			kind: 1,
		},
		TargetZ: {
			literal: "LogicType.TargetZ",
			value: 90,
			kind: 1,
		},
		Temperature: {
			literal: "LogicType.Temperature",
			value: 6,
			kind: 1,
		},
		TemperatureDifferentialEfficiency: {
			literal: "LogicType.TemperatureDifferentialEfficiency",
			value: 151,
			kind: 1,
		},
		TemperatureExternal: {
			literal: "LogicType.TemperatureExternal",
			value: 73,
			kind: 1,
		},
		TemperatureInput: {
			literal: "LogicType.TemperatureInput",
			value: 107,
			kind: 1,
		},
		TemperatureInput2: {
			literal: "LogicType.TemperatureInput2",
			value: 117,
			kind: 1,
		},
		TemperatureOutput: {
			literal: "LogicType.TemperatureOutput",
			value: 127,
			kind: 1,
		},
		TemperatureOutput2: {
			literal: "LogicType.TemperatureOutput2",
			value: 137,
			kind: 1,
		},
		TemperatureSetting: {
			literal: "LogicType.TemperatureSetting",
			value: 72,
			kind: 1,
		},
		Throttle: {
			literal: "LogicType.Throttle",
			value: 154,
			kind: 1,
		},
		Thrust: {
			literal: "LogicType.Thrust",
			value: 221,
			kind: 1,
		},
		ThrustToWeight: {
			literal: "LogicType.ThrustToWeight",
			value: 223,
			kind: 1,
		},
		Time: {
			literal: "LogicType.Time",
			value: 102,
			kind: 1,
		},
		TimeToDestination: {
			literal: "LogicType.TimeToDestination",
			value: 224,
			kind: 1,
		},
		TotalMoles: {
			literal: "LogicType.TotalMoles",
			value: 66,
			kind: 1,
		},
		TotalMolesInput: {
			literal: "LogicType.TotalMolesInput",
			value: 115,
			kind: 1,
		},
		TotalMolesInput2: {
			literal: "LogicType.TotalMolesInput2",
			value: 125,
			kind: 1,
		},
		TotalMolesOutput: {
			literal: "LogicType.TotalMolesOutput",
			value: 135,
			kind: 1,
		},
		TotalMolesOutput2: {
			literal: "LogicType.TotalMolesOutput2",
			value: 145,
			kind: 1,
		},
		TotalQuantity: {
			literal: "LogicType.TotalQuantity",
			value: 265,
			kind: 1,
		},
		TrueAnomaly: {
			literal: "LogicType.TrueAnomaly",
			value: 251,
			kind: 1,
		},
		VelocityMagnitude: {
			literal: "LogicType.VelocityMagnitude",
			value: 79,
			kind: 1,
		},
		VelocityRelativeX: {
			literal: "LogicType.VelocityRelativeX",
			value: 80,
			kind: 1,
		},
		VelocityRelativeY: {
			literal: "LogicType.VelocityRelativeY",
			value: 81,
			kind: 1,
		},
		VelocityRelativeZ: {
			literal: "LogicType.VelocityRelativeZ",
			value: 82,
			kind: 1,
		},
		VelocityX: {
			literal: "LogicType.VelocityX",
			value: 231,
			kind: 1,
		},
		VelocityY: {
			literal: "LogicType.VelocityY",
			value: 232,
			kind: 1,
		},
		VelocityZ: {
			literal: "LogicType.VelocityZ",
			value: 233,
			kind: 1,
		},
		Vertical: {
			literal: "LogicType.Vertical",
			value: 21,
			kind: 1,
		},
		VerticalRatio: {
			literal: "LogicType.VerticalRatio",
			value: 35,
			kind: 1,
		},
		Volume: {
			literal: "LogicType.Volume",
			value: 67,
			kind: 1,
		},
		VolumeOfLiquid: {
			literal: "LogicType.VolumeOfLiquid",
			value: 182,
			kind: 1,
		},
		WattsReachingContact: {
			literal: "LogicType.WattsReachingContact",
			value: 164,
			kind: 1,
		},
		Weight: {
			literal: "LogicType.Weight",
			value: 222,
			kind: 1,
		},
		WorkingGasEfficiency: {
			literal: "LogicType.WorkingGasEfficiency",
			value: 105,
			kind: 1,
		},
	},
} satisfies nestedData as nestedData
